import { GridBox, StandardButton, Button } from "std-widgets.slint";
import { CheckBox, ComboBox, TextEdit, ScrollView } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    min-width: 500px;
    min-height: 400px;
    title: "Example GUI";
    VerticalLayout {
        HorizontalLayout {
            alignment: center;
            padding: 10px;
            Text {
                text: "Office Template Helper";
            }
        }

        FileSelector := HorizontalLayout {
            padding-top: 40px;
            width: 100%;
            height: 20%;
            Button {
                width: 100px;
                height: 20px;
                text: "Open File";
                clicked => {
                    // FileDialog::open_single_file("Select a file", "", |file_path| {
                    //     if let Some(path) = file_path {
                    //         file_path_text.text = path;
                    //     } else {
                        //         file_path_text.text = "No file selected";
                        //     }
                        // });
                    }
            }

            Text {
                // id: file_path_text;
                    text: "No file selected";
            }
        }

        // init := HorizontalLayout {
        //     alignment: center;
        //     // This will center the child widget horizontally
        //         Button {
        //         width: 80%;
        //         height: 20px;
        //         text: "Initalize";
        //         clicked => {
        //             // FileDialog::open_single_file("Select a file", "", |file_path| {
        //             //     if let Some(path) = file_path {
        //             //         file_path_text.text = path;
        //             //     } else {
        //                 //         file_path_text.text = "No file selected";
        //                 //     }
        //                 // });
        //             }
        //     }
        // }

        labeled := HorizontalLayout {
            padding-bottom: 0px;
            padding: 10px;
            width: 100%;
            height: 5%;
            Text {
                text: "Program:";
            }

            Text {
                text: "Add-On:";
            }
        }

        settings := HorizontalLayout {
            padding-top: 0px;
            padding-left: 30px;
            padding-right: 30px;
            width: 100%;
            height: 10%;
            GridBox {
                ComboBox {
                    enabled: false;
                    model: ["Program", "Option 2", "Option 3"];
                }

                ComboBox {
                    enabled: false;
                    model: ["Choice A", "Choice B", "Choice C"];
                }
            }
        }

        HorizontalLayout {
            //width: 100%;
            
                //alignment: center; // This will center the child widget horizontally


                // center the text editor
                
                ScrollView {
                TextEdit {
                    min-width: 490px;
                    min-height: 200px;
                    text: "If the add-on does not work: \n    Please select the program and select initialze.";
                    // Since the TextEdit is the only child inside the ScrollView, it will fill the ScrollView's size
                    }
            }
        }

        HorizontalLayout {
            padding-left: 50px;
            padding-right: 30px;
            padding-top: 10px;
            padding-bottom: 20px;
            alignment: space-between;
            Rectangle {
                width: 100px;
            }

            Button {
                width: 40%;
                //height: 20px;
                text: "Start";
                clicked => {
                    request-increase-value();
                }
            }

            CheckBox {
                text: ": Enable Option ";
                checked: false;
            }
        }
        HorizontalLayout {
            alignment: space-between;
            Text {text: "version: 1.0.0";}
            //Text {text: "© 2024";}
            Text {text: "Made with Slint";}
        }

        // HorizontalLayout {
        //     //padding-right: 30px;
        //         GridBox {
        //         StandardButton {
        //             kind: ok;
        //             clicked => {
        //                 request-increase-value();
        //             }
        //         }

        //         StandardButton {
        //             kind: close;
        //             clicked => {
        //                 request-increase-value();
        //             }
        //         }

        //         StandardButton {
        //             kind: reset;
        //             clicked => {
        //                 request-increase-value();
        //             }
        //         }
        //     }
        // }
    }
}
